data:
- action
- bonus_action
- object_interaction
- target
- attack
- damage
- move_on_your_turn
- reaction
- hit
- miss
- prone
- ability
- skill
- proficiency
- critical
- critical_miss
- move
- animation
- from
- to 
- child_tags
- actor_ids
- start_turn
- end_turn
- log
- loc_path
- animation_frames
- stealth
- proficiency