data:
- action
- bonus_action
- object_interaction
- target
- attack
- damage
- move_on_your_turn
- reaction
- hit
- miss
- prone
- ability
- skill
- proficiency
- critical
- critical_hit
- critical_miss
- advantage
- disadvantage
- move
- animation
- from
- to 
- child_tags
- start_turn
- end_turn
- log
- loc_path
- animation_frames
- stealth
- proficiency
- combat_start
- combat_end
- one_handed
- two_handed
- dual_wielding
- melee_attack
- weapon_attack
- command_id
- actor_ids
- actor_id
- engine_state_transition
- target_id
- target_loc
- attacker_id
- attacker_loc
- attack_roll_declared
- attack_roll_completed
- next_round
- gametime_update
- recharge
- short_rest
- long_rest
- initiative
- command_execution_completed